# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-06 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_auto_20170206_1223'),
        ('email', '0002_auto_20170124_1552'),
    ]

    operations = [
    ]
